apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fk118z647-python
  janus-idp.io/tekton: fk118z647-python
  backstage.io/kubernetes-id: fk118z647-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fk118z647-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
