apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fk118z647-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fk118z647-python 
  name: fk118z647-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fk118z647-python 
